name: "Example workflow for Robot Framework"

on:
  push:
  workflow_dispatch:

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Robot and Dependencies
        shell: bash
        run: |
          pip3 install --upgrade \
                  --no-cache-dir \
                  robotframework \
                  robotframework-browser
      - name: Install node deps and python deps for test running
        run: |
          rfbrowser init

      - name: Execute tests
        run: |
          robot --outputdir=results tests 

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: results
          path: ${{ github.workspace }}/results

